import pandas as pd
import matplotlib.pyplot as plt
import json
import sys
import numpy as np

"""
Skyline Visualization Tool (2D).

This script reads the CSV output generated by the Flink Skyline job and renders a 
visual representation of the Skyline (Pareto frontier). It is specifically designed 
for 2-Dimensional data, plotting the resulting points on a scatter graph.

The tool parses the JSON-encoded points from the CSV, reconstructs the geometry, 
and overlays a "step line" to illustrate the area of dominance. This helps visually 
verify the correctness of the algorithm (e.g., confirming no points exist "below and to the left" 
of the skyline in a minimization problem).
"""

# Domain Configuration
# Defines the absolute boundaries of the data space to ensure the visualization 
# reflects the true scale of the dataset relative to the origin.
D_MIN = 0
D_MAX = 10000

"""
Generates and saves a 2D scatter plot of the Skyline.

The function operates by first loading the entire results CSV into a Pandas DataFrame 
and selecting a specific row based on the provided index. It extracts the 'SkylinePoints' 
column, which contains a JSON-serialized list of coordinates, and converts it into a 
NumPy array for numerical processing.

To ensure the "step line" visualization renders correctly, the data points are sorted 
by their X-coordinate. The function then plots the individual points as red markers 
and connects them with a dotted step-line, which visually demarcates the dominance region.

The plot axes are strictly locked to the configured domain (D_MIN to D_MAX) rather than 
autoscaling to the data range. This is critical for assessing how "good" the skyline is; 
points closer to the bottom-left origin (0,0) represent better optimization results.

Inputs:
- csv_file: Path to the CSV file containing Flink results.
- row_index: The specific record index to plot (Defaults to -1 for the most recent result).

Outputs:
- Saves a PNG image named 'skyline_viz_{index}.png'.
- Displays the interactive plot window.
"""
def plot_skyline(csv_file, row_index=-1):
    try:
        df = pd.read_csv(csv_file)
        
        # Extract the specific row and metadata
        row = df.iloc[row_index]
        points_json = row["SkylinePoints"]
        algo_name = row.get("QueryID", "Unknown") 
        
        # Parse the raw JSON string into a NumPy array
        skyline_points = json.loads(points_json)
        skyline_data = np.array(skyline_points)

        # Initialize a square figure to prevent visual distortion of the 2D space
        plt.figure(figsize=(10, 10)) 
        
        if len(skyline_data) > 0:
            # Sort the data by the X-dimension (Column 0).
            # This is required for the matplotlib 'step' function to draw the
            # dominance line correctly from left to right.
            skyline_data = skyline_data[skyline_data[:, 0].argsort()]
            
            # Plot the actual Skyline points
            plt.scatter(skyline_data[:, 0], skyline_data[:, 1], c='red', s=20, label='Skyline', zorder=5)
            
            # Draw the Step Line
            # This dotted line helps visualize the "Pareto Frontier" boundary.
            plt.step(skyline_data[:, 0], skyline_data[:, 1], where='post', linestyle=':', color='red', alpha=0.6)

        # Enforce Fixed Domain View
        # We explicitly set the limits to the full domain range (0-10000) instead of allowing
        # matplotlib to zoom in on the points. This provides context on where the skyline 
        # sits relative to the global search space.
        plt.xlim(D_MIN, D_MAX)
        plt.ylim(D_MIN, D_MAX)
        
        plt.title(f"Skyline: {algo_name} (Count: {len(skyline_data)})")
        plt.xlabel("Dimension 1")
        plt.ylabel("Dimension 2")
        plt.legend()
        plt.grid(True, linestyle='--', alpha=0.5)
        
        output_file = f"skyline_viz_{row_index}.png"
        plt.savefig(output_file)
        print(f"Graph saved to {output_file}")
        plt.show()

    except Exception as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python graph_skyline_2d.py <results.csv> [row_index]")
        sys.exit(1)
        
    csv_path = sys.argv[1]
    idx = int(sys.argv[2]) if len(sys.argv) > 2 else -1
    plot_skyline(csv_path, idx)
